import '../(public)/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Image from 'next/image'
import { Toaster } from 'react-hot-toast'
import Header from './components/header'
import Sidebar from './components/menu'

const mainFontFamily = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-main'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={`${mainFontFamily.variable} scroll-smooth`}>
      <Toaster
        position="top-right"
        reverseOrder={false}
      />
      <body className='overflow-y-hidden bg-zinc-50'>
        {/* <Header /> */}
        <main className='flex h-screen w-screen'>
          <Sidebar />
          {children}

        </main>
      </body>
    </html>
  )
}
