import "../../../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Sidebar from "./components/menu";

const mainFontFamily = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={`${mainFontFamily.variable} scroll-smooth`}>
      <Toaster position="top-right" reverseOrder={false} />
      <body className="overflow-hidden flex flex-col box-border p-0 m-0 dark:bg-slate-900 bg-zinc-50">
        {/* <Header /> */}
        {/* lembrar de ver esse overflow */}
        <main className="h-screen w-screen overflow-auto bg-inherit">
          <Sidebar>{children}</Sidebar>
        </main>
      </body>
    </html>
  );
}
