import '../globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Image from 'next/image'

const mainFontFamily = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-main'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <>
      <html className={`${mainFontFamily.variable} scroll-smooth`}>
        <body className=''>
          <div className='flex h-screen md:w-screen'>
            <div className="lg:flex hidden w-2/3 h-screen bg-cover bg-no-repeat bg-[url('/assets/login-bg.jpg')]">
              <Image
                className="ml-8 flex absolute mt-11"
                src="/assets/logo-branca.svg"
                alt="Logo"
                width={212}
                height={212}
              />
              <div className=" absolute bottom-20 ml-8">
                <h2 className="2xl:text-2xl text-white">Deixe sua casa mais limpa!</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem</p>
              </div>
            </div>
            {children}
          </div>
        </body>
      </html>
    </>
  )
}